theme: jekyll-theme-minimal
logo: <img src="/assets/photos.png" alt="Steven Foulon" width="150" style="border-radius: 50%; margin-top: 1rem;">
title: Steven Foulon
description: Portfolio Data Engineer – Steven Foulon
